(* Graphicspdf Test *)
module Graphics = Graphicspdf

let _ =
  Graphics.open_pdf "graph.pdf";
  Graphics.open_graph " 1280x1024";
  Graphics.set_window_title "My OCaml Document";
  Printf.printf "size is %i by %i\n" (Graphics.size_x ()) (Graphics.size_y ());
  Graphics.moveto 200 200;
  Graphics.rmoveto 20 20;
  Graphics.set_line_width 2;
  Graphics.set_color (Graphics.rgb 200 100 0); 
  Graphics.plot 60 60;
  Graphics.plots [|(61, 61); (62, 62); (63, 63);|];
  Graphics.moveto 10 0;
  Graphics.set_color Graphics.black;
  Graphics.lineto 0 100;
  Graphics.moveto 10 0;
  Graphics.set_color Graphics.white;
  Graphics.lineto 10 100;
  Graphics.moveto 10 0;
  Graphics.set_color Graphics.red;
  Graphics.lineto 20 100;
  Graphics.moveto 10 0;
  Graphics.set_color Graphics.green;
  Graphics.lineto 30 100;
  Graphics.moveto 10 0;
  Graphics.set_color Graphics.blue;
  Graphics.lineto 40 100;
  Graphics.moveto 10 0;
  Graphics.set_color Graphics.yellow;
  Graphics.lineto 50 100;
  Graphics.moveto 10 0;
  Graphics.set_color Graphics.cyan;
  Graphics.lineto 60 100;
  Graphics.moveto 10 0;
  Graphics.set_color Graphics.magenta;
  Graphics.lineto 70 100;
  Graphics.lineto 300 250;
  Graphics.rlineto ~-50 45;
  Printf.printf "currx = %i, curry = %i\n" (Graphics.current_x ()) (Graphics.current_y ());
  let x, y = Graphics.current_point () in
  Printf.printf "currx = %i, curry = %i\n" x y;
  Graphics.curveto (300, 200) (250, 350) (400, 400);
  Graphics.draw_rect 100 100 50 70;
  Graphics.fill_rect 500 500 40 60;
  Graphics.set_color (Graphics.rgb 100 200 50);
  Graphics.draw_poly [|(20, 20); (40, 40); (50, 20);|];
  Graphics.fill_poly [|(20, 220); (40, 240); (50, 220);|];
  Graphics.draw_segments [|(0, 0, 100, 100); (0, 0, 100, 200)|];
  Graphics.draw_circle 200 200 100;
  Graphics.set_color (Graphics.red);
  Graphics.fill_circle 300 600 60;
  Graphics.draw_ellipse 500 500 200 100;
  Graphics.fill_ellipse 400 600 100 200;
  Graphics.set_color Graphics.black;
  Graphics.set_text_size 14;
  Graphics.moveto 100 600;
  Graphics.set_font "Times";
  Graphics.draw_string "The Quick Fox etc...";
  Graphics.moveto 100 580;
  Graphics.set_font "Times-Bold";
  Graphics.draw_string "The Quick Fox etc...";
  Graphics.moveto 100 560;
  Graphics.set_font "Times-Italic";
  Graphics.draw_string "The Quick Fox etc...";
  Graphics.moveto 100 540;
  Graphics.set_font "Times-BoldItalic";
  Graphics.draw_string "The Quick Fox etc...";
  Graphics.moveto 100 520;
  Graphics.set_font "Helvetica";
  Graphics.draw_string "The Quick Fox etc...";
  Graphics.moveto 100 500;
  Graphics.set_font "Helvetica-Bold";
  Graphics.draw_string "The Quick Fox etc...";
  Graphics.moveto 100 480;
  Graphics.set_font "Helvetica-Italic";
  Graphics.draw_string "The Quick Fox etc...";
  Graphics.moveto 100 460;
  Graphics.set_font "Helvetica-BoldItalic";
  Graphics.draw_string "The Quick Fox etc...";
  Graphics.moveto 100 440;
  Graphics.set_font "Courier";
  Graphics.draw_string "The Quick Fox etc...";
  Graphics.moveto 100 420;
  Graphics.set_font "Courier-Bold";
  Graphics.draw_string "The Quick Fox etc...";
  Graphics.moveto 100 400;
  Graphics.set_font "Courier-Italic";
  Graphics.draw_string "The Quick Fox etc...";
  Graphics.moveto 100 380;
  Graphics.set_font "Courier-BoldItalic";
  Graphics.draw_string "The Quick Fox etc...";
  Graphics.moveto 100 360;
  Graphics.set_font "Symbol";
  Graphics.draw_string "The Quick Fox etc...";
  Graphics.moveto 100 340;
  Graphics.set_font "ZapfDingbats";
  Graphics.draw_string "The Quick Fox etc...";
  Graphics.close_graph ()

